name: export-ccache

on:
  workflow_dispatch:
    inputs:
      cache_key:
        required: true

jobs:
  export:
    runs-on: ubuntu-latest

    env:
      KSU_TYPE: ReSukiSU
      KERNEL_VERSION: 6.6.89
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 安装工具
        run: sudo apt-get update && sudo apt-get install -y zstd

      - name: 设置路径
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_${KSU_TYPE}_${KERNEL_VERSION}" >> $GITHUB_ENV

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ inputs.cache_key }}

      - name: 查看缓存
        run: |
          echo "cache-hit=${{ steps.cache.outputs.cache-hit }}"
          ls -lah "${{ env.CCACHE_DIR }}" || true

      - name: 打包
        run: |
          tar --zstd -cf "${{ inputs.cache_key }}.tar.zst" -C "$HOME" ".ccache_${KSU_TYPE}_${KERNEL_VERSION}"

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: exported-${{ inputs.cache_key }}
          path: "*.tar.zst"